spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: online-school-auth-api
          uri: http://online-school-auth-api:8083
          predicates:
            - Path=/server/**
          filters:
            - RewritePath=/server/(?<segment>.*), /server/api/v1/${segment}

        - id: online-school-course-api
          uri: http://online-school-course-api:8082
          predicates:
            - Path=/server/courses/**
          filters:
            - RewritePath=/server/courses/(?<segment>.*), /courses/api/v1/${segment}

        - id: next-assets
          uri: http://online-school-client:3000
          predicates:
            - Path=/_next/static/**
          filters:
            - RewritePath=/_next/static/(?<filename>.*), /_next/static/${filename}

        - id: media-files-ui
          uri: http://online-school-client:3000
          predicates:
            - Path=/assets/**, /images/**, /public/**

        - id: ui
          uri: http://online-school-client:3000
          predicates:
            - Path=/**
          filters: [ ]


      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:8081"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Authorization, Content-Type, Accept"
            allow-credentials: true
            max-age: 1800
  application:
    name: gateway

server:
  port: 8081

metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          request: true
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

logs:
  destination: logstash:3100