spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: authservice
          uri: http://courses-auth-service:8083
          predicates:
            - Path=/server/**
          filters:
            - RewritePath=/server/(?<segment>.*), /server/api/v1/${segment}

        - id: courseservice
          uri: http://courses-microservice:8082
          predicates:
            - Path=/courses/**
          filters:
            - RewritePath=/courses/(?<segment>.*), /courses/api/v1/${segment}

        - id: paymentservice
          uri: http://courses-payment-service:8084
          predicates:
                - Path=/payment/**
          filters:
                - RewritePath=/payment/(?<segment>.*), /payment/api/v1/${segment}

        - id: ui
          uri: http://client:3000
          predicates:
            - Path=/ui/**
          filters:
            - RewritePath=/ui/(?<segment>.*), /${segment}

        - id: next-assets
          uri: http://client:3000
          predicates:
            - Path=/_next/static/**
          filters:
            - RewritePath=/_next/static/(?<filename>.*), /_next/static/${filename}

        - id: media-files-ui
          uri: http://client:3000
          predicates:
              - Path=/assets/**, /images/**, /public/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowed-origins: "http://localhost:8081"
            allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
            allowed-headers: "Authorization, Content-Type, Accept"
            allow-credentials: true
            max-age: 1800
  application:
    name: gateway

server:
  port: 8081

metrics:
  distribution:
    percentiles-histogram:
      http:
        server:
          request: true
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

logs:
  destination: logstash:3100